--
-- PostgreSQL database dump
--


-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bens (
    id smallint NOT NULL,
    nome text NOT NULL,
    valor_aportado numeric(12,2) NOT NULL,
    valor_mercado_manual numeric(12,2),
    data_aquisicao date DEFAULT CURRENT_DATE,
    obs text,
    id_tipo smallint,
    quantidade numeric(18,8) NOT NULL,
    id_moeda smallint NOT NULL,
    circulante boolean NOT NULL,
    encerrado_em timestamp with time zone,
    vida_util_meses smallint,
    valor_residual numeric(8,4),
    CONSTRAINT bens_valor_residual_check CHECK (((valor_residual >= (0)::numeric) AND (valor_residual <= (1)::numeric)))
);


--
-- Name: bens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cat_mov; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cat_mov (
    id smallint NOT NULL,
    nome text NOT NULL,
    id_pai smallint,
    encerrado_em timestamp with time zone
);


--
-- Name: cat_mov_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cat_mov ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cat_mov_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: compromissos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.compromissos (
    id integer NOT NULL,
    data date NOT NULL,
    data_registro timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    data_vencimento date,
    nome character varying(100),
    valor_original numeric(12,2),
    obs text,
    id_natureza smallint,
    id_entidade smallint NOT NULL,
    taxa_juros numeric(8,4),
    tipo_juros text,
    encerrado_em timestamp with time zone,
    CONSTRAINT compromissos_tipo_juros_check CHECK ((tipo_juros = ANY (ARRAY['fixo'::text, 'cdi'::text, 'selic'::text, 'ipca'::text])))
);


--
-- Name: compromissos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.compromissos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compromissos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contas (
    id smallint NOT NULL,
    id_entidade smallint NOT NULL,
    nome text NOT NULL,
    id_tipo smallint NOT NULL,
    obs text,
    id_bem smallint,
    encerrado_em timestamp with time zone
);


--
-- Name: contas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cotacoes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cotacoes (
    id smallint NOT NULL,
    id_moeda smallint NOT NULL,
    cotacao numeric(12,2) NOT NULL
);


--
-- Name: cotacoes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cotacoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cotacoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: entidades; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.entidades (
    id smallint NOT NULL,
    nome character varying(50) NOT NULL,
    id_tipo smallint,
    encerrado_em timestamp with time zone
);


--
-- Name: entidades_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.entidades ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entidades_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: moedas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.moedas (
    id smallint NOT NULL,
    nome text NOT NULL
);


--
-- Name: moedas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.moedas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.moedas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movimentacoes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.movimentacoes (
    id integer NOT NULL,
    id_compromisso integer,
    data_evento date NOT NULL,
    data_registro timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    valor numeric(12,2) NOT NULL,
    operacao character varying(100) NOT NULL,
    obs text,
    id_cat smallint NOT NULL,
    id_bem smallint,
    conta_origem smallint,
    conta_destino smallint,
    data_liquidacao date,
    id_status smallint NOT NULL,
    CONSTRAINT movimentacoes_valor_positivo_check CHECK ((valor >= (0)::numeric))
);


--
-- Name: movimentacoes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.movimentacoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimentacoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: naturezas_compromissos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.naturezas_compromissos (
    id smallint NOT NULL,
    nome character varying(35) NOT NULL,
    natureza character(1),
    CONSTRAINT natureza_compromissos_natureza_chk CHECK ((natureza = ANY (ARRAY['P'::bpchar, 'A'::bpchar])))
);


--
-- Name: naturezas_compromissos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.naturezas_compromissos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.naturezas_compromissos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.status (
    id smallint NOT NULL,
    nome text NOT NULL,
    obs text
);


--
-- Name: status_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipos_bens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tipos_bens (
    id smallint NOT NULL,
    nome text NOT NULL,
    id_pai smallint
);


--
-- Name: tipos_bens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tipos_bens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipos_bens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipos_contas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tipos_contas (
    id smallint NOT NULL,
    nome text NOT NULL,
    obs text
);


--
-- Name: tipos_contas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tipos_contas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipos_contas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipos_entidades; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tipos_entidades (
    id smallint NOT NULL,
    nome text NOT NULL,
    obs text
);


--
-- Name: tipos_entidades_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tipos_entidades ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipos_entidades_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- PostgreSQL database dump complete
--


